name: lint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  markdownlint:
    name: Markdown lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          globs: "docs/**/*.md README.md"
          config: ".markdownlint.yaml"
